# Site settings
title: MilkDroplet
header-img: img/home-bg.jpg
# email: milkdroplet.service@gmail.com
copyright_name: MilkDroplet Game Studio
meta_description: "We're an indie game studio located in Toronto. Currently we're focusing on creating addictive mobile games. We dream of creating worlds where players can dive in and enjoy."
baseurl: ""
url: "https://milkdroplet.com/"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  milkdroplet.service@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
